### ISSUE TITLE
Crash when rendering messages at very wide (e.g. 640x200) resolution

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#474]
Happens when picking up any item. Set resolution to 640x200w, go to doom.wad E1M1 and pick an item.

```
#0    0x00000001000f3444 in I_Error(char const*, ...) at sdl/i_system.cpp:267
#1    0x000000010007afeb in V_DrawPatchInt(PatchInfo*, VBuffer*) at v_patch.cpp:656
#2    0x0000000100081a06 in V_DrawPatchTranslated(int, int, VBuffer*, patch_t*, unsigned char*, bool) at v_video.cpp:450
#3    0x0000000100066ba0 in V_FontWriteTextEx(vtextdraw_t const&) at v_font.cpp:260
#4    0x000000010015d158 in HUDMessageWidget::drawer() at hu_stuff.cpp:414
#5    0x000000010015c908 in HUDWidget::DrawWidgets() at hu_stuff.cpp:165
#6    0x000000010015ca7d in HU_Drawer() at hu_stuff.cpp:275
#7    0x00000001002ff426 in D_Display() at d_main.cpp:618
#8    0x00000001002fd82c in D_DoomMain() at d_main.cpp:1958
#9    0x00000001000e8e2f in main at sdl/i_main.cpp:113
#10    0x00007fff6a177cc9 in start ()
```

On Debug, the following `I_Error` happens:

```
V_DrawPatchInt: bad texturecolumn 4
```

**Comment by Altazimuth** [comment]
Fixed by 5ae9d81a24043b6483c3da261ba501d76e37cf43.
It's not just that, you have to have a wide resolution that is less than 240 high.
